### ISSUE TITLE
Documentation for restopt_problem

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#13]
The documentation for the `restopt_problem` function needs to be completed.

**Comment by dimitri-justeau** [comment]
I set this issue closed. It's ok for me. I do not remember if we talked about it, but I suggest that for documentation issues we can directly commit and push to the main branch, and close the issues. I suggest that we do a final grammar check once we have documented everything, what do you think ?

**Comment by dimitri-justeau** [comment]
Closed with https://github.com/dimitri-justeau/restoptr/commit/bade1075ff9d2620e4c874672d2bf51d5169f50b
