### ISSUE TITLE
Documentation for add_locked_out_constraint

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#16]
The documentation for the `add_locked_out_constraint()` function needs to be completed.

**Comment by dimitri-justeau** [comment]
I set this issue closed. It's ok for me. I do not remember if we talked about it, but I suggest that for documentation issues we can directly commit and push to the main branch, and close the issues. I suggest that we do a final grammar check once we have documented everything, what do you think ?
