### ISSUE TITLE
Package for validating arguments

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#2]
I find it useful to use a package to validate input arguments for funcitons. I noticed that the DESCRIPTION file contained listed `checkmate` as a dependency - should this package be used for validation? I personally use the `assertthat` package - but I'm happy to go with what ever you think is best?

**Comment by dimitri-justeau** [comment]
I don't have a particular opinion on that if you have experience and positive feedbacks with `asserthat`, let's go with it!

**Comment by jeffreyhanson** [comment]
Ok great - thanks!
