### ISSUE TITLE
Documentation for package overview

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#21]
The documentation for the package overview (i.e. `R/package.R`) needs to be completed.

**Comment by dimitri-justeau** [comment]
What is this file useful for ? Do we really need more details here ?

**Comment by jeffreyhanson** [comment]
Ah - sorry, I forgot to respond to your question. This manual entry is useful because it serves as a short README for the package that can be easily opened within R (e.g. using the code `?restoptr`). For example, it could contain a short description and minimal example. Although this manual entry provides much of the same information as in the README, this is still considered useful because it's not easy to open the package README from within an R session (e.g., see https://github.com/tidyverse/dplyr/blob/main/R/dplyr.r). Some people use `${package_name}.R` or `package.R` for this file - but the general idea/purpose is the same.

**Comment by dimitri-justeau** [comment]
Ok I understand, thank you for explaining this ! I will make this documentation then :-)

**Comment by dimitri-justeau** [comment]
Ok I added some documentation in https://github.com/dimitri-justeau/restoptr/commit/6293fa25e45efb167555171b77819f13e02a307b, do you think it is enough ?

**Comment by jeffreyhanson** [comment]
This is amazing - thanks!

**Comment by dimitri-justeau** [comment]
Nice, I close this issue then !
