### ISSUE TITLE
Documentation for solve

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#22]
The documentation for `solve()` is incomplete.

**Comment by dimitri-justeau** [comment]
https://github.com/dimitri-justeau/restoptr/commit/33e0ea65c42e042ce7d42ad37f18db2676712011

**Comment by dimitri-justeau** [comment]
Seeing your comment in https://github.com/dimitri-justeau/restoptr/issues/23, I reopen this issue, I will complete the documentation to explain the output raster values tomorrow.

**Comment by jeffreyhanson** [comment]
Awesome - thanks!

**Comment by dimitri-justeau** [comment]
https://github.com/dimitri-justeau/restoptr/commit/3380593ad8197efa2107bab51b828db21a17d1aa
