### ISSUE TITLE
Tests for solve()

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#23]
Tests for `solve()` are incomplete. Here are some ideas for possible tests:
 1. `solve()` returns a "correct" solutions using a toy problem and 1 solution is requested, 
 2. `solve()` returns 3 "correct" solutions using a toy problem and 3 solutions are requested.
 3. `solve()` returns N "correct" solutions using a toy problem and K (where N << K) solutions are requested and only N solutions exist.
 4.  `solve()` returns helpful error message when an infeasible problem is specified.

**Comment by jeffreyhanson** [comment]
@dimitri-justeau, when drafting the documentation for the `add_locked_out_constraints()` function, I noticed that the solver output a raster with the following values: -1, 0, 1, and 2. What do these values mean? 

Also, should -1 values correspond to values in the input rasters with nodata/NA/missing values? If so, maybe the solve function should automatically coerce/convert these values to missing values when importing the tiff?

**Comment by dimitri-justeau** [comment]
If fixed the Java program, -1 are now NA in output rasters. I explained that 0 is non-habitat, 1 habitat, and 2 restoration in solve documentation.

I also modified solve to return helpful messages: either there is no solutions, targets must be adjusted, or the time limit was to tight and the solver did not have enough time.

I now need to do some adjustments to allow configuring the solver to return several solutions from R.

**Comment by dimitri-justeau** [comment]
Ok, I implemented the tests for solve -- as it is at the moment -- here : https://github.com/dimitri-justeau/restoptr/commit/b021e7791e1e8ccfc036319f9a6f42f5052e424d

I suggest to close this issue. For the multiple solutions option, I opened another dedicated issue, as it is will be a new feature.
