### ISSUE TITLE
Tests for add_compactness_constraint

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#25]
The tests for `add_compactness_constraint()` are incomplete. Here's some ideas for tests:
1. Verify that a solution to a toy problem can be succesfully generated using these constraints.
2. Verify that adding these constraints to a toy problem reduces the compactness of the solution, and that the compactness of the solution does not exceed the specified threshold.

**Comment by dimitri-justeau** [comment]
https://github.com/dimitri-justeau/restoptr/commit/2308f88322bac6d930828ccb85800bfc886d9e05
