### ISSUE TITLE
Tests for add_components_constraint

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#26]
The tests for `add_components_constraint()` are incomplete. Here's some ideas:
1. Verify that solving a toy problem with this constraint yields a solution.
2. Verify that adding this constraint changes a solution.
3. Verify that adding this constraint results in a solution with the correct number of components.

**Comment by dimitri-justeau** [comment]
https://github.com/dimitri-justeau/restoptr/commit/82f2f3cd935539af53bafd1b8a29855f537b0b02

I also implement a `add_connected_constraint`, which is a shortcut to `add_components_constraints(1, 1)`

**Comment by jeffreyhanson** [comment]
> [82f2f3c](https://github.com/dimitri-justeau/restoptr/commit/82f2f3cd935539af53bafd1b8a29855f537b0b02)
> 
> I also implement a `add_connected_constraint`, which is a shortcut to `add_components_constraints(1, 1)`

Ah - that's an awesome idea - thanks!
