### ISSUE TITLE
Tests for add_max_iic_objective

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#28]
The tests for `add_max_iic_objective()` are incomplete. Here's some ideas:
1. Verify that solving a toy problem with this objective yields a "correct" solution.

**Comment by dimitri-justeau** [comment]
https://github.com/dimitri-justeau/restoptr/commit/696b32c2e1023af2d9e8855cbf30d2aec5589263

Also, the tests for max MESH and max IIC where, to my opinion, already sufficient. Please feel free to reopen if you disagree !
