### ISSUE TITLE
Number of connected components

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#3]
I noticed that the function for specifying the number of connected components allows users to specify a range of acceptable values (i.e. using a minimum and maximum value). I was wondering exactly what the use-case for specifying such a range would be? I guess my question is when/why would a user specify such a range, instead of wanting a specific number of components?

**Comment by dimitri-justeau** [comment]
I think it brings more flexibility to allow specifying a range -- which can correspond to a single value. A typical use-case would be: "I have a fixed budget for restoration, and I am willing to restore up to 3 distinct areas, as long as it maximizes the benefits on the effective mesh size index". Do you think it can bring confusion to users?

**Comment by jeffreyhanson** [comment]
Yeah that makes sense to me. Although it could potentially lead to some confusion, if it's well documented I don't think it would cause an issue? E.g., we could provide examples showing how to (1) only get solutions with a certain number of components (by setting the min and max parameters as the same), and (2) get solution with a range of components (by setting different min and max parameters).

**Comment by dimitri-justeau** [comment]
I don't think so either, documentation will indeed be the key !

**Comment by jeffreyhanson** [comment]
Ok great - thanks for clarifying that, I'll close this issue now.
