### ISSUE TITLE
Tests for add_restorable_constraint

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#30]
The tests for `add_restorable_constraint()` are incomplete. Here's some ideas:
1. Verify that solving a toy problem with this constraint yields a solution.
2. Verify that adding this constraint changes a solution.
3. Verify that adding this constraint results in a solution with the correct area.

**Comment by dimitri-justeau** [comment]
https://github.com/dimitri-justeau/restoptr/commit/dede00e3bee222ebd40edd41bc6b2274ef8626a5
