### ISSUE TITLE
Tests for add_settings

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#31]
The tests for `add_settings()` are incomplete. Here's some ideas:
1. Verify that default parameters yield expected results.
2. Verify that changing each parameter to a non-default value results in expected behavior.

**Comment by dimitri-justeau** [comment]
https://github.com/dimitri-justeau/restoptr/commit/6b95578e9530ca984fe095fd996b6e15c9824705
