### ISSUE TITLE
Tests for internal terra functions

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#32]
The tests for the internal terra functions (see `R/terra_io.R`) are incomplete. Here's some ideas:
1. Verify that the return expected behavior (this will be useful to track down any further changes to the terra API).

**Comment by dimitri-justeau** [comment]
https://github.com/dimitri-justeau/restoptr/commit/6840c5bf9d45f751868d9eeb91053d0a1b519435
