### ISSUE TITLE
README

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#33]
It would be great to update the README. I suggest it would be helpful to (1) update it with a short demo showcasing the package, (2) update the citation details, and (3) finishing the getting help section. @dimitri-justeau, can you think of anything else?

**Comment by dimitri-justeau** [comment]
https://github.com/dimitri-justeau/restoptr/commit/7585bb0af2098df76e57f6c11cd431b86e347f42
