### ISSUE TITLE
email

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#39]
Hi @dimitri-justeau,

Sorry - I'm trying to respond to your previous email but my emails keep getting bounced. Specifically, I receive this automatic response:

![image](https://user-images.githubusercontent.com/3610005/160474774-f0811b45-6a79-4fde-a655-364d28e30e57.png)

I don't suppose you have any ideas on how to fix this, or is there a different email address I could try?

**Comment by jeffreyhanson** [comment]
If not I can try sending from a different email address of mine - just let me know?

**Comment by dimitri-justeau** [comment]
Oh that's strange... You can use either ***@***.*** or
***@***.*** !

Le mar. 29 mars 2022 à 06:46, Jeff Hanson ***@***.***> a
écrit :

**Comment by jeffreyhanson** [comment]
Ah - sorry, GitHub has replaced those email addresses with asterisks. Could you send me an email with those addresses? I can still receive emails from your main address, it's just I can't seem to send them to it.

**Comment by dimitri-justeau** [comment]
Yep, I sent you a mail from my gmail address, did you receive it ?

**Comment by jeffreyhanson** [comment]
Yeah - thanks!
