### ISSUE TITLE
Accessibility data

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#4]
My understanding from reading the restopt readme is that the accessibility data specify which planning units (grid cells) are available for restoration, and these data are optional. Is that correct? If so, it seems like these data serve the same purpose as locking out planning units from the soltion - is that right? If so, I wonder if it might be helpful to reframe/rename the R functions as locked out constraints. How does that sound? Sorry if I'm missing something - this is just an idea.

**Comment by dimitri-justeau** [comment]
You are totally right, I do not see any problem renaming this as a locked out constraint, even more, if most PrioritizR or Marxan users are used to this vocabulary.

**Comment by jeffreyhanson** [comment]
Ok excellent! Yeah, the locked out terminology is originally from Marxan - priroitizr just uses the same terminology as Marxan where posssible to make things easier. 

I suppose the downside with this approach is that restopt and restoptr will have different terminology/option names. Would that cause any problems or confusion? In other words, do you envision this package as a direct interface to restopt (such that all options/teriminology should be exactly the same), or a bit more standalone (such that the options/terminology can be a bit different in some cases)? What do you think?

**Comment by dimitri-justeau** [comment]
I am ok to use Marxan - prioritizr terminology, I can also change the parameter name in the `restopt` (Java) to ensure consistency. The only thing (as you might have noticed in the branch `api_dim`, is that the `accessible` value specifies the planning units (PUs) that are available for restoration, thus the locked out PUs are all PUs except those having the `accessible` value. What I suggested is to have two parameters in the locked out constraint:

  - `raster_value` : which corresponds to the raster value of PUs to be locked out (or not locked out).
  - `lock_out` is a Boolean, indicating whether `raster_values` indicates PUs to lockout (TRUE), or PUs not to lockout (FALSE). With FALSE as the default value to keep the current behaviour of restopt.

The advantage is that within a single raster, the user can have different areas that can be used in separate problems (e.g. administrative areas). This is how we used `restopt` originally, as we had to design one restoration area for each district of our study area.

**Comment by jeffreyhanson** [comment]
Thanks for explaining that! So, if the user had a raster of binary values indicating which grid cells should be locked out (1 = lock out, 0 = don't lock out), then they would do something like this?

```
p <- 
  restopt_problem(habitat_data, restoration_data) %>%
  add_max_iic_objective() %>%
  add_locked_out_constraints(data = accessibility_data, value = 1, lock_out = TRUE)
```

If so, this makes sense to me - but I wonder if something simpler might be more helpful for beginner users? E.g., in prioritizr, we require users to specify locked out data using logical/binary values (1 = locked out, 0 = not), and leave it up to the user to specify prepare the data. What do you think about that? So e.g., the equivalent could be:

```
p <- 
  restopt_problem(habitat_data, restoration_data) %>%
  add_max_iic_objective() %>%
  add_locked_out_constraints(data = accessibility_data)
```

Advanced users could leverage the terra R package to easily convert integer rasters into binary rasters. For example, if the user had a range of different integer values corresponding to different scenarios for locking out different places, this could be done using something like this (e.g., asssuming you wanted lock out planning units with a value of 5):

```
p <- 
  restopt_problem(habitat_data, restoration_data) %>%
  add_max_iic_objective() %>%
  add_locked_out_constraints(data = round(accessibility_data == 5))
```

What do you think?

**Comment by dimitri-justeau** [comment]
I really like this idea, having a simple and easy default behaviour, and an easy way to make and advanced use with the terra package. I'm in favour of this, I'll try to implement it !

**Comment by jeffreyhanson** [comment]
Thanks for implememting this! Since you've merged thw PR with this implementation, I'll close this issue now.
