### ISSUE TITLE
Remove `add_settings` ?

### ISSUE THREAD

**Issue by dimitri-justeau** [dimitri-justeau/restoptr#40]
Currently, the `add_settings` method is used to configure the precision, the time limit, and the number of solutions.

However, the precision parameter only applies for `set_max_mesh_objective()` and `set_max_iic_objective()` objectives, but it is useless for `set_no_objective()` (only constraint satisfaction), and it will be useless for some upcoming optimization objectives (`set_min_components`, `set_min_restorable`, etc).

Also, the time limit and the number of solutions parameters refer to the solving process. So I think that they would more useful as parameters of the solve method. Indeed, if a user solves a problem with 30s time limit and finds out that it is not enough, he will just have to recall the solve method with another time limit, instead of having to modify the restopt problem. @jeffreyhanson What is your opinion on this?

**Comment by jeffreyhanson** [comment]
Sorry for my slow response - yeah, that makes a lot of sense - I completely agree!

**Comment by dimitri-justeau** [comment]
Nice ! I suggest that we fix all other issues before doing this modification, to avoid messing up too much of the code and documentation.

**Comment by jeffreyhanson** [comment]
Sounds good!

**Comment by jeffreyhanson** [comment]
Just to check, if we're adding a gap parameter to the codebase, would it be worth keeping this function? I agree it would be good to move the precision parameters to the relevant objective functions. So, this function could be used to specify (1) run time limits, (2) number of solutions, and (3) an optimality gap? How does that sound?

**Comment by dimitri-justeau** [comment]
Hum, I have mitigated feelings:

In favour of removing the function:
   - It would save one line of code to re-run the same problem with different parameters.
   - The restopt problem would only describe the problem while solving aspects would all be specific to the `solve` function.
 
In favour of keeping the function:
   - Parameters will remain stored after the problem is solved, and can be printed.
   - It involves less code modification, which is good if we target a quick first release.

I think I vote for the second option, mainly for the last argument, as I think that not much is needed to be ready for the first release.

**Comment by dimitri-justeau** [comment]
**Update:** Thinking about it, settings like the optimality gap and the precision are more related to the objective, so the ideal case would be storing them in the objective. However, I'm afraid that it could be confusing in the end. So I wonder if the best option is not to keep the `set_settings` function as is, and explain in the documentation that some settings are only useful for some objectives (e.g. the precision setting is only used by non-integer objectives). Are you okay with this (i.e. do nothing and keep things as they are) ?

**Comment by jeffreyhanson** [comment]
Sorry - I forgot to respond to your question. Yeah, I think that sounds like the way to go. Since we're in agreement and no further changes are needed AFAIK, I'll close the issue.
