### ISSUE TITLE
package title

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#42]
After merging the Java code into this repository and making R the package the main interferace, I wonder if it wouldbe worth renaming the title of the package? Currently, the title is "restoptr: Interface to the 'Restopt' Ecological Restoration Planning Software". With these changes, I wonder if "restoptr: Ecological Restoration Software", or "restoptr: Ecological Restoration Optimization" might work better?

**Comment by dimitri-justeau** [comment]
Yes I totally agree with this! Could we go with "restoptr: Ecological Restoration Planning with/in R" ?

**Comment by jeffreyhanson** [comment]
Yeah, I really like this! Unfortunately, CRAN seems to have a policy that packages shouldn't have "in R" or "with R" in the title (e.g., see https://github.com/ThinkR-open/prepare-for-cran#do-not-put-in-r-or-with-r-in-the-package-title). CRAN did asked us to rename the prioritizr package title at one point, but we managed to covince them that the package already had its title for several years (at that point in time) so this would confuse/annoy users. So, how about "restoptr: Ecological Restoration Planning"?

**Comment by dimitri-justeau** [comment]
Ok I understand, let's with "restoptr: Ecological Restoration Planning" then, if it can facilitate the CRAN submission process :-)

**Comment by dimitri-justeau** [comment]
I changed the title of the package !
