### ISSUE TITLE
readme instructions

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#45]
@dimitri-justeau, I had to use the following terminal commands to rebuild the Java file. Does this look right to you? If so, maybe it's worth updating the README with these commands? Also, perhaps it might be worth providing commands that don't depend on particular version numbers? What do you think? Sorry if I'm doing something wrong :)

```
git pull
git submodule update --init --recursive
cd restopt
mvn clean package -DskipTests
cp target/restopt-*.jar ../java/
```

**Comment by dimitri-justeau** [comment]
I updated the information in https://github.com/dimitri-justeau/restoptr/commit/827d5cba1bf4be44c8b1a58b2f8da67282df1bd4

Actually the command `git pull --recurse-submodules` should be sufficient to update both restoptr and restopt. Can you confirm before we close the issue? I also modified the line for copying the jar as you suggested, that's great thank you !

**Comment by jeffreyhanson** [comment]
Thanks! Hmm, when I run that command in a fresh repo, the `restopt` folder remains empty. My git client also says that the `restopt` submodule is "uninitialized". So it doesn't seem to work for me? My git version is 2.32.0 - what version do you have?

**Comment by dimitri-justeau** [comment]
Oh yes you are right, sorry, the `git submodule update --init --recursive` was necessary, the `git pull --recurse-submodules` is only necessary to update the submodule. I updated the README.

**Comment by jeffreyhanson** [comment]
Awesome - thanks!
