### ISSUE TITLE
optimality_proven values in get_metadata()

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#46]
I noticed that the "optimality_proven" column in the result from `get_metadata()` contains either `"true"` or `"false"` values. I was wondering if it might be useful for this column to contain `logical` values instead (i.e. `TRUE` or `FALSE`)?

**Comment by dimitri-justeau** [comment]
You are right  ! I fixed it in https://github.com/dimitri-justeau/restoptr/commit/5d64ad90ca19661ae9d1b731030a76b992b660e5

**Comment by jeffreyhanson** [comment]
Awesome - thanks!
