### ISSUE TITLE
Bug in Github action "documentation" ?

### ISSUE THREAD

**Issue by dimitri-justeau** [dimitri-justeau/restoptr#49]
I'm struggling with the `urlchecker::check_url()` function used in the "Documentation" Github action... It fails because of URLs that actually work (e.g. https://www.oracle.com/java/technologies/downloads/). I tried a `devtools::check(cran=TRUE)` and I had no WARNING or NOTE about URLs. @jeffreyhanson do you have an idea about what's happening here? Thank you !

**Comment by jeffreyhanson** [comment]
Yeah, the package checks run by `devtools::check()` don't check for URL issues. When submitting a package to CRAN, they will automatically run checks on all the URLs to make sure they are valid. Unfortunately, the software CRAN uses has a very high false positive rate - -meaning that it will flag URLs as having issues even if they are totally fine -- and (in my experience) they will reject submissions with URLs that have any issues (e.g., even if URL works and it's simply a redirect, such as using http instead of https). I've had to remove URLs from documentation or update them to address these issues.

**Comment by jeffreyhanson** [comment]
I'm not seeing any issues with this URL though `"https://www.oracle.com/java/technologies/downloads/"` when I run it on my computer - what error do you get?

**Comment by jeffreyhanson** [comment]
Sorry - just realized this error is on the CI not a local run.

**Comment by jeffreyhanson** [comment]
Just pulled the latest main branch, and can now replicate the URL errors locally.

**Comment by jeffreyhanson** [comment]
It seems we can fix the link in the citation file by using the DOI URL instead (i.e., https://doi.org/10.1111/1365-2664.13803) and the ORACLE URL issues by linking to the specific file downloads (e.g., https://download.oracle.com/java/18/latest/jdk-18_linux-x64_bin.deb). What do you think? If that sounds good, I could prepare a PR?

**Comment by dimitri-justeau** [comment]
Hi Jeff, sorry for the late answer, I was enjoying some holiday time with my family :-) As you prefer, I can also try to fix it today, I have some time for it! It looks like the doi.org urls are also causing some problems with CRAN, but let's try!

**Comment by dimitri-justeau** [comment]
Well, I fixed the citation file by simply removing the link (doi.org also causes problems). For Oracle, it seems like Oracle has set protection that causes the timeout error when the URL is requested from an automated process... I am not really in favour of linking specific downloads, as it will trigger a not necessarily wanted download in users' browser, and because it does not let the choice to select a specific version etc. Actually, I think that the easiest solution would be removing the Oracle links (i.e. just mentioning Oracle), it might also encourage users to use OpenJDK or GraalVM, that are both open-source, contrarily to OracleJDK. What do you think of that ?

**Comment by jeffreyhanson** [comment]
No worries! Yeah - that fix sounds good to me.

**Comment by dimitri-justeau** [comment]
Ok thank you ! It's fixed with https://github.com/dimitri-justeau/restoptr/commit/4394a96eb11522f7a7b21e3aef70cd3b0a55d975
