### ISSUE TITLE
maxDiam

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#5]
My understanding is that the `maxDiam` parameter is mandatory (from reading the restopt README). Is that correct? If so, maybe this is something that needs to be specified as part of the problem constructor, rather than an optional constraint? Or could we set a default value (e.g. `Inf`) if the user does not manually specify a maximum diameter?

**Comment by dimitri-justeau** [comment]
Actually, it should not be mandatory. When it is specified the smallest enclosing circle constraint is posted. If not specified then there is no restriction over the spatial extent of the solution.

**Comment by jeffreyhanson** [comment]
Ah ok - thanks for clarifying that.
