### ISSUE TITLE
compareGeom does not have stopiffalse argument

### ISSUE THREAD

**Issue by rhijmans** [dimitri-justeau/restoptr#55]
"restoptr" now breaks with the development version of "terra". This is because of a call to `terra::compareGeom` in  `restoptr::restopt_solution` :

```
    terra::compareGeom(
      solution_raster, restopt_problem$data$existing_habitat, stopiffalse = FALSE
    )
``` 

`compareGeom` does not have the argument "stopiffalse" (it does have `stopOnError`). This error went undetected in previous versions, but that has now been fixed.

**Comment by dimitri-justeau** [comment]
Hello, thank you for pointing out this error, I just fixed it in https://github.com/dimitri-justeau/restoptr/commit/5aa9daf486146e9f1c7266cac8bb1847584f17af , and I am submitting the fixed package to CRAN.
