### ISSUE TITLE
minProportion

### ISSUE THREAD

**Issue by jeffreyhanson** [dimitri-justeau/restoptr#6]
This issue is similar to #5 - should the `minProportion` parameter be considered mandatory or optinal? If mandatory, where should it be specified? If optional, should we just set a default value of 1 if the user doesn't specify a value?

**Comment by dimitri-justeau** [comment]
I never thought about that but it would make total sense to set it at 1 by default!

**Comment by jeffreyhanson** [comment]
Ok - awesome! So, let's we'll add a custom constraint function to specify the `minProportion` value?

**Comment by dimitri-justeau** [comment]
I'd rather have juste one `add_restorable_constraint` with `minProportion` as an optional argument, as this parameter is not really a constraint in itself.

**Comment by jeffreyhanson** [comment]
Sounds good - I'll close this issue now.
